### ISSUE TITLE
Common Parent Theme Overrides

### ISSUE THREAD

**Issue by mathetos** [ahmadawais/_child#1]
Really appreciate your attention to detail on this simple "Child Theme Boilerplate". I personally wanted to take it a little further and provide a framework for some common Parent Theme overrides that I implement very often based on our article: https://wordimpress.com/removing-styles-scripts-from-your-wordpress-parent-theme/

Not sure if you're interested in a Pull Request or not for this, but wanted to show you what I mean:
https://github.com/mathetos/_child

Thanks!

**Comment by ahmadawais** [comment]
Hey, @mathetos!
Thanks for dropping by. I get where you are coming from, but a simple generic boilerplate might not have these cleanup functions. But we can have a separate branch called `cleanup`.

I have kept this boilerplate intentionally simple since everyone has a few hacks when they create a child theme. I myself stripped some functions which I used to display the user that he is using a child theme instead of the parent one. 

So, if you are interested in PR for a branch, that'd be cool, though, I'd like to keep master branch as a boilerplate. 

What are your thoughts?

**Comment by mathetos** [comment]
Sounds good. I played with my fork a bit today and I think I'd need to clean it up a bit more. But let me know when you create the branch and I'll submit over to that.

Overall, I thought of this a lot like Bill Erikson's Core Functionality plugin. He basically puts a lot of useful things in there, but comments them out so users can ignore them or use them or add on to them as they see fit. So it still stays lean, but there's a good base for what the power of a child theme can do for you.

**Comment by ahmadawais** [comment]
@mathetos Sounds great. I have a habbit of keeping different branches for that. E.g. My theme boilerplate has branches which have boilerplate integration with different plugins.

I have creaed the branch https://github.com/ahmadawais/_child/tree/cleanup looking forward to the PR.
