### ISSUE TITLE
CSS folfer for child theme

### ISSUE THREAD

**Issue by aurovrata** [ahmadawais/_child#3]
NIce boilerplate.

I have noted many new themes are relinquishing the root `style.css` file for a css folder with a collection of css files.  This permits cleaner css styling as each file can concentrate on particular sections/pages of the site but can also be enqueued separately to reduce page loads.

Would you consider adding this to your child boilerplate, by encluding a `css/style.css` file enqueued in the `functions.php` file?

**Comment by ahmadawais** [comment]
@aurovrata Enqueueing multiple CSS files is a bad idea at least until the full adoption of HTTP/2 standard. And even if you want to do that, this is just a boilerplate, you are supposed to modify it every time you use it. 

So, that'd be your thing to do. Also, check out [WPGulp](https://github.com/ahmadawais/WPGulp) since that is what you are talking about. That's my workflow for separate files with Sass.
